### ISSUE TITLE
json not getting created

### ISSUE THREAD

**Issue by ankur7721** [rinkstiekema/PDF-Table-Structure-Recognition-using-deep-learning#7]
After using pix2pix model, I am unable to generate json. Code runs fine, there is no error but on analyzing I found `rulers.py` has some problem i guess, couldn't figure out though.
P.S I am not using any skip options

Can you please help me point it out.

**Comment by rinkstiekema** [comment]
I'm a little confused by what you are trying to do. The final result should be a CSV file. The JSON file is generated by PDFFigures2 and is used in the extraction process, but is not a goal on it's own. Can you ellaborate I little more what you are trying to do?

**Comment by leyuan** [comment]
@rinkstiekema I think the issue is 
`no main manifest attribute, in pdffigures2.jar`

and there is no corresponding json files created in the json directory. I have tried couple downloads and went to the source code as you pointed in another PR, is it possible to share the jar file that you use as well?

Thanks

**Comment by rinkstiekema** [comment]
I am using the one that is in the repository (https://github.com/rinkstiekema/PDF-Table-Structure-Recognition-using-deep-learning/blob/master/pipeline/pdffigures2.jar), I'm not quite sure what is going wrong with your version. The jar does include the manifest in the META-INF folder.
